
project_id = "velasbzeojyjsysiuftf"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
tenant_id = "realtime-dev"

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54329
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://velasbzeojyjsysiuftf.supabase.co/auth/v1/callback"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.analyze-lead]
verify_jwt = true

[functions.chatbot-ai]
verify_jwt = true

[functions.chatbot-deep-thinking]
verify_jwt = true

[functions.create-subscription-checkout]
verify_jwt = true

[functions.generate-funnel-ai]
verify_jwt = true

[functions.generate-interactive-funnel-ai]
verify_jwt = true

[functions.reset-password]
verify_jwt = false

[functions.signup]
verify_jwt = false


[functions.generate-modular-funnel-ai]
verify_jwt = true

[functions.generate-scene-image]
verify_jwt = true

[edge-runtime]
enabled = true
port = 54330

[analytics]
enabled = false
port = 54327
vector_port = 54328
